ems/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('user.urls'), name='user'),

    path('', include('leave.urls'), name='leave'),

    path('', include('documents.urls'), name='documents')
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

leave/urls.py
from django.urls import path
from .views import *

app_name = "leave"

urlpatterns = [
    # Dashboards
    path('dashboard/', dashboard, name='dashboard'),

    # Json leave
    path('json_pending_leave/', jsonPendingLeave, name='json_pending_leave'),
    path('json_accepted_leave/', jsonAcceptedLeave, name='json_accepted_leave'),
    path('json_rejected_leave/', jsonRejectedLeave, name='json_rejected_leave'),

    path('calendar/', calendar, name='calendar'),

    # Export xls  
    path('export_leave_xls/', export_leave_xls, name='export_leave_xls'),
    path('export_employyes_leaves_xls/', export_employyes_leaves_xls, name='export_employyes_leaves_xls'),
    path('export_employyes_limits_xls/', export_employyes_limits_xls, name='export_employyes_limits_xls'),

    # Leaves
    path('add_leave', addLeave, name='add_leave'),
    path('list_leaves', listLeaves, name='list_leaves'),
    path('view_vacation_limits', detailVacationLimits, name='view_vacation_limits'),

    # Leaves view
    path('view_pending_leaves', viewPendingLeaves, name='view_pending_leaves'),
    path('view_accepted_leaves', viewAcceptedLeaves, name='view_accepted_leaves'),
    path('view_rejected_leaves', viewRejectedLeaves, name='view_rejected_leaves'),

    # Notifications
    path('notifications/', viewNotifications, name='view_notifications'),
    path('<int:notification_id>/accept_notifications/', acceptNotification, name='accept_notifications'),

    # Leaves action
    path('<int:leave_id>/detail_leave', detailLeave, name='detail_leave'),
    path('<int:leave_id>/accept_leave', acceptLeave, name='accept_leave'),
    path('<int:leave_id>/reject_leave', rejectLeave, name='reject_leave'),
    path('<int:user_id>/update_vacation_limits', updateVacationLimitPage, name='update_vacation_limits'),

    # Leave limits
    path('view_employees_limits', viewListEmployeesLimits, name='view_list_employees_limits'),
    path('<int:employee_id>/view_employees_limits', viewEmployeesLimits, name='view_employees_limits')

]

leave/forms.py
import datetime
from django.core.exceptions import ValidationError
# from django.utils.translation import ugettext_lazy as _

from django import forms
from .models import Leave, AcceptLeave, RejectLeave, VacationLimit

class CreateLeaveForm(forms.ModelForm): 

    class Meta: 
        model = Leave
        fields = "__all__"
        exclude = ['employee', 'status']
        widgets = {
            'leave_type': forms.Select(attrs={'class': 'form-control'}),
            'leave_date': forms.DateInput(format='%Y-%m-%d', attrs={'id':'datepicker', 'placeholder': 'Date leave', 'class': 'form-control'}),
            'return_date': forms.DateInput(format='%Y-%m-%d', attrs={'id':'datepicker1', 'placeholder': 'Date return', 'class': 'form-control'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', "rows":5, "cols":20}),
        }


    def clean(self):
        cleaned_data = super().clean()
        leave_date = self.cleaned_data.get('leave_date')
        return_date = self.cleaned_data.get('return_date')

        # Check if a return_date is greater than leave_date
        if return_date < datetime.date.today():
            raise forms.ValidationError("Return date should be greater than leave date.")
        # Check if a date is not in the past. 
        if leave_date < datetime.date.today():
            raise forms.ValidationError("Leave date should be greater than today.")
        # Check if a return_date is greater than leave_date
        if leave_date > return_date:
            raise forms.ValidationError("Leave date can't be greater than return date.")



class CreateAcceptLeaveForm(forms.ModelForm):

    class Meta:
        model = AcceptLeave
        fields = []
        exclude = ['status', 'leave']


class CreateRejectLeaveForm(forms.ModelForm):

    class Meta:
        model = RejectLeave
        fields = []
        exclude = ['status', 'leave']


class UpdateVacationLimitForm(forms.ModelForm):

    class Meta:
        model = VacationLimit
        fields = "__all__"
        exclude = ["employee"]
        widgets = {
            'normal_days_constant': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter constant normal days'}),
            'normal_days': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter normal days'}),
            'children_days_constant': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter constant children days'}),
            'children_days': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter children days'}),
            'request_days_constant': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter constant request days'}),
            'request_days': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter request number'}),
        }

    def __init__(self, *args, **kwargs):
        super(UpdateVacationLimitForm, self).__init__(*args, **kwargs)
        self.fields['normal_days_constant'].required == True
        self.fields['normal_days'].required == True
        self.fields['children_days_constant'].required == True
        self.fields['children_days'].required == True
        self.fields['request_days_constant'].required == True
        self.fields['request_days'].required == True

    

class ExportLeaveForm(forms.Form):

    leave_date = forms.DateField(widget=forms.TextInput(attrs={'id':'datepicker', 'placeholder': 'Date leave', 'class': 'form-control'}))
    return_date = forms.DateField(widget=forms.TextInput(attrs={'id':'datepicker1', 'placeholder': 'Date leave', 'class': 'form-control'}))

leave/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from .models import Leave, VacationLimit, AcceptLeave, RejectLeave, LeaveNotificationEmployee
from user.decorators import unauthenticated_user, allowed_users, admin_only, check_regulation
from .forms import CreateLeaveForm, CreateAcceptLeaveForm, CreateRejectLeaveForm, UpdateVacationLimitForm, ExportLeaveForm
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from user.models import SalaryInfo
from documents.models import RegulationsStatus

# Paginations
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# For xls export
import xlwt
# Messages
from django.contrib import messages
# For count days
import numpy as np
# Change date 
import datetime

@allowed_users(allowed_roles=['employee', 'supervisor'])
def export_leave_xls(request):
    form = ExportLeaveForm()
    if request.method == 'POST':

        user = request.user

        leave_date = request.POST.get('leave_date')
        return_date = request.POST.get('return_date')
   

        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename="Leaves-{}-{}.xls"'.format(user.first_name, user.last_name)
        wb = xlwt.Workbook(encoding='utf-8')
        ws = wb.add_sheet('Leaves')

        # Sheet header, first row
        row_num = 0
        font_style = xlwt.XFStyle()
        font_style.font.bold = True
        columns = ['Type leave', 'Leave date', 'Return date', 'Count days', 'Comment', 'Status']
        for col_num in range(len(columns)):
            ws.write(row_num, col_num, columns[col_num], font_style)

        # Sheet body, remaining rows
        font_style = xlwt.XFStyle()
        rows = Leave.objects.filter(Q(employee=user) & Q(leave_date__range=(leave_date, return_date)) & Q(return_date__range=(leave_date, return_date))).values_list('leave_type', 'leave_date', 'return_date', 'days', 'comment', 'status')
        for row in rows:
            row_num += 1
            for col_num in range(len(row)):
                # Change date format in excel
                if col_num == 1 or col_num == 2:
                    font_style.num_format_str = 'D-MM-YYYY'
                else:
                    font_style.num_format_str = '0'
                ws.write(row_num, col_num, row[col_num], font_style)
        wb.save(response)
        if not rows:
            messages.warning(request, "In this range you doesn't have a holidays")
            return redirect('/export_leave_xls')
        else:
            return response

    context = {
        'form': form
    }
    template_name = "leave/export_leave_xls.html"
    return render(request, template_name, context)

@allowed_users(allowed_roles=['supervisor', 'admin'])
def export_employyes_leaves_xls(request):
   
    file_name = datetime.datetime.today().strftime("%Y-%m-%d")

    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Leaves-{}.xls"'.format(file_name)
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Leaves')

    # Sheet header, first row
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    columns = ['First name', 'Last name', 'Type leave', 'Leave date', 'Return date', 'Count days', 'Comment', 'Status']
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()
    rows = Leave.objects.filter(employee__userprofile__boss=request.user.boss).values_list('employee__first_name', 'employee__last_name', 'leave_type', 'leave_date', 'return_date', 'days', 'comment', 'status')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            # Change date format in excel
            if col_num == 3 or col_num == 4:
                font_style.num_format_str = 'D-MM-YYYY'
            else:
                font_style.num_format_str = '0'
            ws.write(row_num, col_num, row[col_num], font_style)
    wb.save(response)
    if not rows:
        messages.warning(request, "Employees dosn't have a holidays")
        return redirect('/export_leave_xls')
    else:
        return response


@allowed_users(allowed_roles=['supervisor', 'admin'])
def export_employyes_limits_xls(request):
   
    file_name = datetime.datetime.today().strftime("%Y-%m-%d")

    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="VacationLimits-{}.xls"'.format(file_name)
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Limits')

    # Sheet header, first row
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    columns = ['First name', 'Last name', 'Normal days costant', 'Normal days', 'Children days costant', 'Children days', 'Request days costant', 'Request days']
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()
    rows = VacationLimit.objects.filter(employee__userprofile__boss=request.user.boss).values_list('employee__first_name', 'employee__last_name', 'normal_days_constant', 'normal_days', 'children_days_constant', 'children_days', 'request_days_constant', 'request_days')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)
    wb.save(response)
    if not rows:
        messages.warning(request, "You doesn't have any employees")
        return redirect('/export_leave_xls')
    else:
        return response


@allowed_users(allowed_roles=['employee', 'supervisor'])
def addLeave(request, *args):
    user = request.user
    vacation_limits = VacationLimit.objects.get(employee=user)
    user_leaves = Leave.objects.filter(employee=user)
    form = CreateLeaveForm()

    if request.method == 'POST':
        leave_date = request.POST.get('leave_date')
        return_date = request.POST.get('return_date')
        leave_type = request.POST.get('leave_type')

        leave_date = datetime.datetime.strptime(leave_date, '%Y-%m-%d').date()
        return_date = datetime.datetime.strptime(return_date, '%Y-%m-%d').date()
        check = True

        # Check if user has a leaves in given dates
        if user_leaves:
            for leave in user_leaves:
                if leave_date <= leave.leave_date <= return_date:
                    check = False
            # If user hasn't a leaves in given dates
            if check:
                holiday_days = np.busday_count(leave_date, return_date) + 1
                # Check all types of leaves
                if leave_type == 'Vacation leave':
                    if vacation_limits.normal_days >= holiday_days:
                        form = CreateLeaveForm(request.POST or None)
                        if form.is_valid():
                            form.instance.employee = user
                            form.instance.days = holiday_days
                            form.save()
                            messages.success(request, "You request has been send")
                            return redirect('/list_leaves')
                    else:
                        messages.warning(request, "You don't have enough days")
                elif leave_type == 'Vacation childcare':
                    if vacation_limits.children_days >= holiday_days:
                        form = CreateLeaveForm(request.POST or None)
                        if form.is_valid():
                            form.instance.employee = user
                            form.instance.days = holiday_days
                            form.save()
                            messages.success(request, "You request has been send")
                            return redirect('/list_leaves')
                    else:
                        messages.warning(request, "You don't have enough days")
                elif leave_type == 'Vacation on demand':
                    if vacation_limits.request_days >= holiday_days:
                        form = CreateLeaveForm(request.POST or None)
                        if form.is_valid():
                            form.instance.employee = user
                            form.instance.days = holiday_days
                            form.save()
                            messages.success(request, "You request has been send")
                            return redirect('/list_leaves')
                    else:
                        messages.warning(request, "You don't have enough days")
                else:
                    form = CreateLeaveForm(request.POST or None)
                    if form.is_valid():
                        form.instance.employee = user
                        form.instance.days = holiday_days
                        form.save()
                        messages.success(request, "You request has been send")
                        return redirect('/list_leaves')
            else:
                messages.warning(request, "You have leave in these days")
        else:
            holiday_days = np.busday_count(leave_date, return_date) + 1
            if vacation_limits.normal_days > holiday_days:
                form = CreateLeaveForm(request.POST or None)
                if form.is_valid():
                    form.instance.employee = user
                    form.instance.days = holiday_days
                    form.save()
                    messages.success(request, "You request has been send")
                    return redirect('/list_leaves')

    context = {
        'form': form,
        'user_leaves': user_leaves,
    }

    return render(request, 'leave/add_leave.html', context)

leave/templates/leave/accept_leave.html
{% block content %}
<div class="modal fade accept_leave" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Accept leave</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to accept this leave?</p>
        </div>
        <div class="modal-footer">
            <form method="POST" action="{% url 'leave:accept_leave' unique_leave.id %}">
            {% csrf_token %}
            <input class="btn btn-lg btn-primary" type="Submit" value="Accept">
            </form>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
</div>
{% endblock content %}


{% comment %} <h1>Are you sure you want to accept this leave?</h1>
<form method="POST" action="">
{% csrf_token %}
<input class="btn btn-lg btn-primary" type="Submit">
</form>
<a class="btn btn-lg btn-secondary" href="">No</a> {% endcomment %}

leave/templates/leave/add_leave.html
{% extends "ems/base.html" %}

{% block title %}
    Add leave
{% endblock title %}

{% block content %}

<script>

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var today = new Date();
    var dd = String(today.getDate()).padStart(2, '0');
    var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
    var yyyy = today.getFullYear();
    today = yyyy + '-' + mm + '-' + dd;
    var calendar = new FullCalendar.Calendar(calendarEl, {
      
      plugins: [ 'interaction', 'dayGrid' ],
      defaultDate: today,
      height: 600,
      editable: false,
      eventLimit: false, // allow "more" link when too many events
      firstDay: 1,
      eventSources: [

        // Pending
        {
          url: '/json_pending_leave', // pedning user leaves
          color: '#007bff',    // color blue for pedning leaves
          textColor: 'white'  // font color white for pedning leaves
        },
        // Accepted
        {
          url: '/json_accepted_leave', // pedning user leaves
          color: '#28a745',    // color blue for pedning leaves
          textColor: 'white'  // font color white for pedning leaves
        },
        // Rejected
        {
          url: '/json_rejected_leave', // pedning user leaves
          color: '#dc3545',    // color blue for pedning leaves
          textColor: 'white'  // font color white for pedning leaves
        } 

      ]

    });

    calendar.render();
  });

</script>
<div class="row justify-content-start mb-3">  
  <span class="ml-3" style="font-size:13px;">Calendar Legend: </span>
  <div class="row ml-2">
    <span class="badge badge-primary ml-3 mr-3">Pending</span>
    <span class="badge badge-success ml-3 mr-3">Accepted</span>
    <span class="badge badge-danger ml-3 mr-3">Rejected</span>
  </div>
</div>


<form method="POST" action="">
    {% csrf_token %}
          {% if form.errors %}
          {% for field in form %}
              {% for error in field.errors %}
                  <div class="alert alert-danger">
                      <strong>{{ error|escape }}</strong>
                  </div>
              {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endif %}
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label for="validationServer01">Leave Type</label>
            {{form.leave_type}}
            <hr>
            <label for="validationServer01">Leave Date</label>
            {{form.leave_date}}
            <hr>
            <label for="validationServer01">Return Date</label>
            {{form.return_date}}
            <hr>
            <label for="validationServer01">Comment</label>
            {{form.comment}}
            <hr>
            <button class="btn btn-lg btn-primary" type="submit">Add leave</button>
        </div>
        <div class="col-md-8 mb-3">
            <div class="m-3" id='calendar'></div>
        </div>
    </div>
</form>

<!-- For datepicker -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>
<script>
    $('#datepicker').datepicker({disableDaysOfWeek: [0, 6], weekStartDay: 1, uiLibrary: 'bootstrap4', format: 'yyyy-mm-dd'});
    $('#datepicker1').datepicker({disableDaysOfWeek: [0, 6], weekStartDay: 1, uiLibrary: 'bootstrap4', format: 'yyyy-mm-dd'});
</script>
{% endblock content %}

leave/templates/leave/reject_leave.html
{% block content %}
<div class="modal fade reject_leave" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Reject leave</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to reject this leave?</p>
        </div>
        <div class="modal-footer">
            <form method="POST" action="{% url 'leave:reject_leave' unique_leave.id %}">
            {% csrf_token %}
            <input class="btn btn-lg btn-primary" type="Submit" value="Reject">
            </form>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
</div>

{% endblock content %}

leave/templates/leave/view_accepted_leave.html
{% extends "ems/base.html" %}
{% load static %}
{% block title %}
    Accepted leave
{% endblock title %}
{% block content %}
{% include "ems/messages.html" %}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="m-0 font-weight-bold text-primary">Accepted Leaves</h1>
            <a href="{% url 'leave:export_employyes_leaves_xls' %}" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm mt-3"><i class="fas fa-download fa-sm text-white-50"></i>Generate Leaves Report</a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Type leave</th>
                <th>Leave Date</th>
                <th>Return Date</th>
                <th>Comment</th>
                <th>Status</th>
                <th>Enter</th>
            </tr>
            </thead>
            <tbody>
            {% for leave in emplooyee_leaves %}
            <tr>
                <td>{{leave.employee.first_name}}</td>
                <td>{{leave.employee.last_name}}</td>
                <td>{{leave.leave_type}}</td>
                <td>{{leave.leave_date}}</td>
                <td>{{leave.return_date}}</td>
                <td>{{leave.comment}}</td>
                <td>{{leave.status}}</td>
                <td><a class="btn btn-primary" href="{{ leave.get_detail_url }}" style="margin:auto; display:block;">View Details</a></td>
            </tr>
            {% endfor %}            
            </tbody>
        </table>
        </div>
    </div>
</div>

{% endblock content %}

leave/templates/leave/view_list_employees_limits.html
{% extends "ems/base.html" %}
{% load static %}
{% block title %}
    Accepted leave
{% endblock title %}
{% block content %}
{% include "ems/messages.html" %}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="m-0 font-weight-bold text-primary">Your limits employees</h1>
            <a href="{% url 'leave:export_employyes_limits_xls' %}" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm mt-3"><i class="fas fa-download fa-sm text-white-50"></i>Generate Vacation Limits Report</a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Enter</th>
            </tr>
            </thead>
            <tbody>
            {% for employee in employees %}
            <tr>
                <td>{{employee.first_name}}</td>
                <td>{{employee.last_name}}</td>
                <td><a class="btn btn-primary" href="{% url 'leave:view_employees_limits' employee.id %}" style="margin:auto; display:block;">View Emloyee limits</a></td>
            </tr>
            {% endfor %}            
            </tbody>
        </table>
        </div>
    </div>
</div>

{% endblock content %}

leave/templates/leave/view_notifications.html
{% extends "ems/base.html" %}
{% block title %}
    Detail leave
{% endblock title %}

{% block content %}

<style>
    .date{
        display: block;
        width: 230px;
        float: left;
        font-weight: 500;
    }
    .notification{
        display: block;
        float: left;
        padding-right: 20px;
    }
    .icon{
        display: block;
        float: right;
        font-size: 12px;
        color: green;
    }

</style>

{% include "ems/messages.html" %}

<div class="row justify-content-center">
    <div class="col-lg-10">
        {% if notificat %}
        <ul class="list-group">
            {% for n in notificat %}
                {% if not n.read %}
                    <a class="list-group-item mb-2" href="{% url 'leave:accept_notifications' n.id %}"><span class="date {% if not n.read %}font-weight-bold {% endif %}">{{n.date_created|date:"d-m-Y H:m:s"}}</span><span class="notification {% if not n.read %}font-weight-bold {% endif %}">{{ n.notification }}</span><i class="icon {% if not n.read %} fas fa-times {% else %} fas fa-check {% endif %} "></i></a>
                {% endif %}
                {% if n.read %}
                    <li class="list-group-item mb-2"><span class="date {% if not n.read %}font-weight-bold {% endif %}">{{n.date_created|date:"d-m-Y H:m:s"}}</span><span class="notification {% if not n.read %}font-weight-bold {% endif %}">{{ n.notification }}</span><i class="icon {% if not n.read %} fas fa-times {% else %} fas fa-check {% endif %} "></i></li>
                {% endif %}
            {% endfor %}
        </ul> 
        {% include "leave/pagination/pagination.html" with page=notificat %}
        {% else %}
        <ul class="list-group">
            <li class="list-group-item mb-2"><span>You does't have any notifications</span></li>  
        </ul>  
        {% endif %}
    </div>
</div>

{% endblock content %}

leave/templates/leave/view_pending_leave.html
{% extends "ems/base.html" %}
{% load static %}
{% block title %}
    Pending leaves
{% endblock title %}
{% block content %}
{% include "ems/messages.html" %}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="m-0 font-weight-bold text-primary">Pending Leaves</h1>
            <a href="{% url 'leave:export_employyes_leaves_xls' %}" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm mt-3"><i class="fas fa-download fa-sm text-white-50"></i>Generate Leaves Report</a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Type leave</th>
                <th>Leave Date</th>
                <th>Return Date</th>
                <th>Comment</th>
                <th>Status</th>
                <th>Enter</th>
            </tr>
            </thead>
            <tbody>
            {% for leave in emplooyee_leaves %}
            <tr>
                <td>{{leave.employee.first_name}}</td>
                <td>{{leave.employee.last_name}}</td>
                <td>{{leave.leave_type}}</td>
                <td>{{leave.leave_date}}</td>
                <td>{{leave.return_date}}</td>
                <td>
                    {% if leave.comment %}
                        {{leave.comment}}
                    {% else %}
                        No comment
                    {% endif %}
                </td>
                <td>{{leave.status}}</td>
                <td><a class="btn btn-primary" href="{{ leave.get_detail_url }}" style="margin:auto; display:block;">View Details</a></td>
            </tr>
            {% endfor %}            
            </tbody>
        </table>
        </div>
    </div>
</div>

{% endblock content %}

leave/templates/leave/view_rejected_leave.html
{% extends "ems/base.html" %}
{% load static %}
{% block title %}
    Rejected leaves
{% endblock title %}
{% block content %}
{% include "ems/messages.html" %}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="m-0 font-weight-bold text-primary">Rejected Leaves</h1>
            <a href="{% url 'leave:export_employyes_leaves_xls' %}" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm mt-3"><i class="fas fa-download fa-sm text-white-50"></i>Generate Leaves Report</a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Type leave</th>
                <th>Leave Date</th>
                <th>Return Date</th>
                <th>Comment</th>
                <th>Status</th>
                <th>Enter</th>
            </tr>
            </thead>
            <tbody>
            {% for leave in emplooyee_leaves %}
            <tr>
                <td>{{leave.employee.first_name}}</td>
                <td>{{leave.employee.last_name}}</td>
                <td>{{leave.leave_type}}</td>
                <td>{{leave.leave_date}}</td>
                <td>{{leave.return_date}}</td>
                <td>{{leave.comment}}</td>
                <td>{{leave.status}}</td>
                <td><a class="btn btn-primary text-center" href="{{ leave.get_detail_url }}" style="margin:auto; display:block;">View Details</a></td>
            </tr>
            {% endfor %}            
            </tbody>
        </table>
        </div>
    </div>
</div>

{% endblock content %}