documents/urls.py
from django.urls import path
from .views import *

app_name = "documents"

urlpatterns = [
    path('add_regulation/', addRegulation, name='add_regulation'),
    path('view_list_regulations/', viewListRegulations, name="view_list_regulations"),
    path('<int:regulation_id>/detail_regulation/', viewDetailRegulation, name="view_detail_regulation"),
    path('view_list_regulations_user/', viewListRegulationsForUser, name="view_list_regulations_user"),
    path('<int:regulation_id>/detail_regulation_user/', viewDetailRegulationForUsers, name="view_detail_regulation_for_users"),
    path('<int:regulation_id>/accept_regulation/', acceptRegulation, name="accept_regulation"),
]

ems/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('user.urls'), name='user'),

    path('', include('leave.urls'), name='leave'),

    path('', include('documents.urls'), name='documents')
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

leave/urls.py
from django.urls import path
from .views import *

app_name = "leave"

urlpatterns = [
    # Dashboards
    path('dashboard/', dashboard, name='dashboard'),

    # Json leave
    path('json_pending_leave/', jsonPendingLeave, name='json_pending_leave'),
    path('json_accepted_leave/', jsonAcceptedLeave, name='json_accepted_leave'),
    path('json_rejected_leave/', jsonRejectedLeave, name='json_rejected_leave'),

    path('calendar/', calendar, name='calendar'),

    # Export xls  
    path('export_leave_xls/', export_leave_xls, name='export_leave_xls'),
    path('export_employyes_leaves_xls/', export_employyes_leaves_xls, name='export_employyes_leaves_xls'),
    path('export_employyes_limits_xls/', export_employyes_limits_xls, name='export_employyes_limits_xls'),

    # Leaves
    path('add_leave', addLeave, name='add_leave'),
    path('list_leaves', listLeaves, name='list_leaves'),
    path('view_vacation_limits', detailVacationLimits, name='view_vacation_limits'),

    # Leaves view
    path('view_pending_leaves', viewPendingLeaves, name='view_pending_leaves'),
    path('view_accepted_leaves', viewAcceptedLeaves, name='view_accepted_leaves'),
    path('view_rejected_leaves', viewRejectedLeaves, name='view_rejected_leaves'),

    # Notifications
    path('notifications/', viewNotifications, name='view_notifications'),
    path('<int:notification_id>/accept_notifications/', acceptNotification, name='accept_notifications'),

    # Leaves action
    path('<int:leave_id>/detail_leave', detailLeave, name='detail_leave'),
    path('<int:leave_id>/accept_leave', acceptLeave, name='accept_leave'),
    path('<int:leave_id>/reject_leave', rejectLeave, name='reject_leave'),
    path('<int:user_id>/update_vacation_limits', updateVacationLimitPage, name='update_vacation_limits'),

    # Leave limits
    path('view_employees_limits', viewListEmployeesLimits, name='view_list_employees_limits'),
    path('<int:employee_id>/view_employees_limits', viewEmployeesLimits, name='view_employees_limits')

]

user/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from .views import *
from django.contrib.auth import views as auth_views


app_name = "user"

urlpatterns = [
    path('', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('users/', users, name='users'),
    path('add_user/', addEmployeePage, name='add_user'),

    path('<int:user_id>/view_user_info/', viewUser, name='view_user_info'),

    path('<int:user_id>/delete_user/', deleteUserPage, name='delete_user'),

    path('<int:user_id>/update_base_info/', updateBaseInfoPage, name='update_base_info'),
    path('<int:user_id>/update_userprofile_info/', updateUserprofileInfoPage, name='update_userprofile_info'),
    path('<int:user_id>/update_salaryinfo_info/', updateSalaryInfoPage, name='update_salaryinfo_info'),
    path('<int:user_id>/update_bankinfo_info/', updateBankInfoPage, name='update_bankinfo_info'),
    path('<int:user_id>/set_new_password/', downloadUserPassword, name='set_new_password'),
    path('<int:user_id>/update_profile_picture/', updateProfilePicturePage, name='update_profile_picture'),


    path('user_info/', infoUser, name='info_user'),
    path('settings_page/', settingsPage, name='settings_page'),
    path('activity_log/', activityPage, name='activity_log'),

    # Change password
    path('change_password/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('user:password_change_done')), name='password_change'),
    path('change_password/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Change username
    path('change_username/', changeUsername, name="change_username"),
]

ems/templates/ems/sidebar.html
{% load user_tags %}

<!-- Page Wrapper -->
<div id="wrapper">

<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <!-- Admin -->

  {% if request.user|has_group:'admin' %}
  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'leave:dashboard' %}">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Employee<small> system</small></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Leaves
  </div>
  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Employee Leaves</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Leaves:</h6>
        <a class="collapse-item" href="{% url 'leave:view_pending_leaves' %}">Pending leaves</a>
        <a class="collapse-item" href="{% url 'leave:view_accepted_leaves' %}">Accepted leaves</a>
        <a class="collapse-item" href="{% url 'leave:view_rejected_leaves' %}">Rejected leaves</a>
        <a class="collapse-item" href="{% url 'leave:view_list_employees_limits' %}">Employee limit leaves</a>
        <a class="collapse-item" href="{% url 'leave:export_employyes_leaves_xls' %}">Generate leaves report</a>
        <a class="collapse-item" href="{% url 'leave:export_employyes_limits_xls' %}">Generate limits report</a>
      </div>
    </div>
  </li>

    <!-- Nav Item - Charts -->
  <li class="nav-item">
    <a class="nav-link" href="charts.html">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Charts leaves</span></a>
  </li>

  <!-- Nav Item - Users -->
  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Heading -->
  <div class="sidebar-heading">
    User Management
  </div>
  <!-- Nav Item - Users -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEmployees" aria-expanded="true" aria-controls="collapsePages">
      <i class="fas fa-fw fa-folder"></i>
      <span>Employees</span>
    </a>
    <div id="collapseEmployees" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Settings:</h6>

        <a class="collapse-item" href="{% url 'user:users' %}">Yours employess</a>
      </div>
    </div>
  </li>


  {% endif %}

  <!-- Supervisor -->

  {% if request.user|has_groups:'supervisor' %}
  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'leave:dashboard' %}">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Employee<small>system</small></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Leaves
  </div>
  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Emlpoyee Leaves</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Leaves:</h6>
        <a class="collapse-item" href="{% url 'leave:view_pending_leaves' %}">Pending leaves</a>
        <a class="collapse-item" href="{% url 'leave:view_accepted_leaves' %}">Accepted leaves</a>
        <a class="collapse-item" href="{% url 'leave:view_rejected_leaves' %}">Rejected leaves</a>
        <a class="collapse-item" href="{% url 'leave:view_list_employees_limits' %}">Employee limit leaves</a>
        <a class="collapse-item" href="{% url 'leave:export_employyes_leaves_xls' %}">Generate leaves report</a>
        <a class="collapse-item" href="{% url 'leave:export_employyes_limits_xls' %}">Generate limits report</a>
      </div>
    </div>
  </li>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLeave" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Your Leaves</span>
    </a>
    <div id="collapseLeave" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Your Leaves:</h6>
        <a class="collapse-item" href="{% url 'leave:add_leave' %}">Add leave</a>
        <a class="collapse-item" href="{% url 'leave:list_leaves' %}">Lists leaves</a>
        <a class="collapse-item" href="{% url 'leave:calendar' %}">Calendar</a>
        <a class="collapse-item" href="{% url 'leave:view_vacation_limits' %}">Your limit leaves</a>
        <a class="collapse-item" href="{% url 'leave:export_leave_xls' %}">Reports</a>
      </div>
    </div>
  </li>

    <!-- Nav Item - Charts -->
  <li class="nav-item">
    <a class="nav-link" href="charts.html">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Charts leaves</span></a>
  </li>
  
  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Documents
  </div>
  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-wrench"></i>
      <span>Documents</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Documents:</h6>
        <a class="collapse-item" href="{% url 'documents:view_list_regulations_user' %}">Regulations</a>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Heading -->
  <div class="sidebar-heading">
    User Management
  </div>
  <!-- Nav Item - Users -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEmployees" aria-expanded="true" aria-controls="collapsePages">
      <i class="fas fa-fw fa-folder"></i>
      <span>Info Employees</span>
    </a>
    <div id="collapseEmployees" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Settings:</h6>
        <a class="collapse-item" href="{% url 'user:users' %}">Yours employess</a>
      </div>
    </div>
  </li>

  {% endif %}




  {% if request.user|has_groups:'hr' %}
  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'leave:dashboard' %}">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Employee<small>system</small></div>
  </a>
  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Heading -->
  <div class="sidebar-heading">
    Documents
  </div>
  <!-- Regulations -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseRegulations" aria-expanded="true" aria-controls="collapsePages">
      <i class="fas fa-fw fa-folder"></i>
      <span>Regulations</span>
    </a>
    <div id="collapseRegulations" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Regulations:</h6>
        <a class="collapse-item" href="{% url 'documents:add_regulation' %}">Add Regulation</a>
        <a class="collapse-item" href="{% url 'documents:view_list_regulations' %}">View send regulations</a>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Heading -->
  <div class="sidebar-heading">
    User Management
  </div>
  <!-- Nav Item - Users -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEmployees" aria-expanded="true" aria-controls="collapsePages">
      <i class="fas fa-fw fa-folder"></i>
      <span>Employees</span>
    </a>
    <div id="collapseEmployees" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Settings:</h6>
        <a class="collapse-item" href="{% url 'user:add_user' %}">Add Employee</a>
        <a class="collapse-item" href="{% url 'user:users' %}">Employess</a>
      </div>
    </div>
  </li>

  {% endif %}

  {% if request.user|has_groups:'employee' %}
  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'leave:dashboard' %}">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Employee<small>system</small></div>
  </a>


  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Leaves
  </div>
  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLeave" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Leaves</span>
    </a>
    <div id="collapseLeave" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Leaves:</h6>
        <a class="collapse-item" href="{% url 'leave:add_leave' %}">Add leave</a>
        <a class="collapse-item" href="{% url 'leave:list_leaves' %}">Lists leaves</a>
        <a class="collapse-item" href="{% url 'leave:calendar' %}">Calendar</a>
        <a class="collapse-item" href="{% url 'leave:view_vacation_limits' %}">Your limit leaves</a>
        <a class="collapse-item" href="{% url 'leave:export_leave_xls' %}">Reports</a>
      </div>
    </div>
  </li>
  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Documents
  </div>
  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-wrench"></i>
      <span>Documents</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Documents:</h6>
        <a class="collapse-item" href="{% url 'documents:view_list_regulations_user' %}">Regulations</a>
      </div>
    </div>
  </li>
  {% endif %}


  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Account
  </div>
  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
      <i class="fas fa-fw fa-folder"></i>
      <span>Account</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Profile:</h6>
        <a class="collapse-item" href="{% url 'user:info_user' %}">Information about you</a>
        <a class="collapse-item" href="{% url 'user:settings_page' %}">Settings</a>
        <a class="collapse-item" href="{% url 'user:logout' %}">Logout</a>
      </div>
    </div>
  </li>
  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

ems/templates/ems/topbar.html
<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

<!-- Main Content -->
<div id="content">

<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
        <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
        </button>
        </div>
    </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
            <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
            </div>
        </form>
        </div>
    </li>
    {% if notifications %}

    <!-- Nav Item - Alerts -->
    <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        {% if notifications_all %}
            <span class="badge badge-danger badge-counter">
                {{notifications_all}}
            </span>
        {% endif %}
        </a>
        <!-- Dropdown - Alerts -->
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
            Alerts Center Leaves
        </h6>
        {% for notification in notifications %}

        <a class="dropdown-item d-flex align-items-center" href="{% url 'leave:accept_notifications' notification.id %}">
            <div class="mr-3">
            <div class="icon-circle {% if not notification.read %} bg-warning {% else %} bg-success {% endif %} ">
                <i class="{% if not notification.read %} fas fa-exclamation-triangle text-white {% else %} fas fa-check {% endif %} "></i>
            </div>
            </div>
            <div>
            <div class="small text-gray-500">{{notification.date_created}}</div>
            <span class="{% if not notification.read %}font-weight-bold {% endif %}">{{notification.notification}}</span>
            </div>
        </a>
            
        {% endfor %}
        <a class="dropdown-item text-center small text-gray-500" href="{% url 'leave:view_notifications' %}">Show All Alerts</a>
        </div>
    </li>
    {% else %}
    {% endif %}

    <!-- Nav Item - Messages -->
    <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <!-- Counter - Messages -->
        <span class="badge badge-danger badge-counter">7</span>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
            Message Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
            <div class="status-indicator bg-success"></div>
            </div>
            <div class="font-weight-bold">
            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
            <div class="small text-gray-500">Emily Fowler · 58m</div>
            </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
            <div class="status-indicator"></div>
            </div>
            <div>
            <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
            <div class="small text-gray-500">Jae Chun · 1d</div>
            </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
            <div class="status-indicator bg-warning"></div>
            </div>
            <div>
            <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
            </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
            <div class="status-indicator bg-success"></div>
            </div>
            <div>
            <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
            <div class="small text-gray-500">Chicken the Dog · 2w</div>
            </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
        </div>
    </li>

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.first_name }}  {{ request.user.last_name }}</span>
        <img class="img-profile rounded-circle" src="{{ request.user.userprofile.image.url }}">
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="{% url 'user:info_user' %}">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Profile
        </a>
        <a class="dropdown-item" href="{% url 'user:settings_page' %}">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Settings
        </a>
        <a class="dropdown-item" href="{% url 'user:activity_log' %}">
            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
            Activity Log
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'user:logout' %}" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
        </a>
        </div>
    </li>

    </ul>

</nav>
<!-- End of Topbar -->

 <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'user:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>