ems/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('user.urls'), name='user'),

    path('', include('leave.urls'), name='leave'),

    path('', include('documents.urls'), name='documents')
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from .views import *
from django.contrib.auth import views as auth_views


app_name = "user"

urlpatterns = [
    path('', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('users/', users, name='users'),
    path('add_user/', addEmployeePage, name='add_user'),

    path('<int:user_id>/view_user_info/', viewUser, name='view_user_info'),

    path('<int:user_id>/delete_user/', deleteUserPage, name='delete_user'),

    path('<int:user_id>/update_base_info/', updateBaseInfoPage, name='update_base_info'),
    path('<int:user_id>/update_userprofile_info/', updateUserprofileInfoPage, name='update_userprofile_info'),
    path('<int:user_id>/update_salaryinfo_info/', updateSalaryInfoPage, name='update_salaryinfo_info'),
    path('<int:user_id>/update_bankinfo_info/', updateBankInfoPage, name='update_bankinfo_info'),
    path('<int:user_id>/set_new_password/', downloadUserPassword, name='set_new_password'),
    path('<int:user_id>/update_profile_picture/', updateProfilePicturePage, name='update_profile_picture'),


    path('user_info/', infoUser, name='info_user'),
    path('settings_page/', settingsPage, name='settings_page'),
    path('activity_log/', activityPage, name='activity_log'),

    # Change password
    path('change_password/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('user:password_change_done')), name='password_change'),
    path('change_password/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Change username
    path('change_username/', changeUsername, name="change_username"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User


class Firm(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    nip = models.CharField(max_length=12)

    def __str__(self):
        return self.name


class Section(models.Model):
    
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class OnlyDirectorManager(models.Manager):
    def get_queryset(self):
        return super(OnlyDirectorManager, self).get_queryset().filter(user__groups__name='admin')


class OnlySupervisorManager(models.Manager):
    def get_queryset(self):
        return super(OnlySupervisorManager, self).get_queryset().filter(user__groups__name='supervisor')


class Boss(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, null=True, blank= True, on_delete=models.CASCADE)


    objects = models.Manager()
    only_director_role = OnlyDirectorManager()
    only_supervisor_role = OnlySupervisorManager()

    def __str__(self):
        return self.user.username


class UserProfile(models.Model):

    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    
    boss = models.ForeignKey(Boss, null=True, on_delete=models.CASCADE)
    firm = models.ForeignKey(Firm, null=True, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, null=True, blank=True, on_delete=models.CASCADE)

    country = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    street = models.CharField(max_length=50, null=True, blank=True)
    zip_code = models.CharField(max_length=8, null=True, blank=True)
    phone_number = models.IntegerField(null=True, blank=True)
    possition = models.CharField(max_length=50, null=True, blank=True)
    birth_date = models.DateField(null=True)

    image = models.ImageField(default="profile_pic.png", null=True, blank=True, upload_to='profile')

    def __str__(self):
        return self.user.username


class BankInfo(models.Model):
    employee = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)

    bank_name = models.CharField(max_length=50, null=True, blank=True)
    bank_number = models.CharField(max_length=28, null=True, blank=True)

    def __str__(self):
        return self.employee.username


class SalaryInfo(models.Model):
    employee = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)

    CONTRACT = (
        ('contract of employment', 'contract of employment'),
        ('contract work', 'contract work'),
        ('contract of mandate', 'contract of mandate'),
    )
    
    salary = models.IntegerField(null=True, blank=True)
    year_salary = models.IntegerField(null=True, blank=True)
    type_contract = models.CharField(max_length=100, null=True, blank=True, choices=CONTRACT)


    def __str__(self):
        return self.employee.first_name + " " + str(self.salary)

user/views.py
from django.shortcuts import render, redirect, HttpResponse
from .decorators import unauthenticated_user, allowed_users, admin_only
from .forms import CreateUserForm, UpdateUserProfileForm, LoginForm, UpdateUserForm, UpdateUsernameForm, UpdateSalaryInfoForm, UpdateUserProfileEmployeeForm, UpdateBankInfoForm, updateProfilePictureForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.models import User, Group

from .models import UserProfile, Boss
from django.db.models import Q
from django.urls import reverse

import io
from django.http import FileResponse
from reportlab.pdfgen import canvas

from django.contrib.auth.decorators import login_required
import random

# Pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@allowed_users(allowed_roles=['hr'])
def addEmployeePage(request):
    form = CreateUserForm()
    
    if request.method == 'POST':
        form = CreateUserForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)

            # Set a new password
            password = User.objects.make_random_password(length=9, allowed_chars="abcdefghjkmnpqrstuvwxyz01234567889")
            user.set_password(password)
            user.save()

            # Add user to group
            group_name = request.POST.get('group_name')
            g = Group.objects.get(name=group_name)
            g.user_set.add(user)

            # Add model Boss if role supervisor
            group_name = Group.objects.get(user=user).name
            if group_name == 'supervisor':
                Boss.objects.create(
                    user=user,
                )

            # redirect to update user page with message
            username = form.cleaned_data.get('username')
            messages.success(request,  'Account was created for ' + username + '. New password for ' + username + ' it ' + password)
            return redirect('/{}/update_userprofile_info/'.format(user.id))


    groups = Group.objects.all().exclude(Q(name='admin'))
    context = {
        'form': form,
        'groups': groups
    }
    return render(request, 'user/add_user.html', context)


@allowed_users(allowed_roles=['hr', 'admin', 'supervisor'])
def downloadUserPassword(request, user_id):
    user = User.objects.get(id=user_id)
    # Set a new password
    password = User.objects.make_random_password(length=9, allowed_chars="abcdefghjkmnpqrstuvwxyz01234567889")
    user.set_password(password)
    user.save()

    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()

    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(20, 800, "Password: {}  Username: {} ".format(password, user.username))

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename='{}{}.pdf'.format(user.first_name, user.last_name))


@allowed_users(allowed_roles=['hr', 'admin', 'supervisor'])
def viewUser(request, user_id):
    user = User.objects.get(id=user_id)

    context = {
        'user': user,
    }

    return render(request, 'user/detail_change_user.html', context)


@allowed_users(allowed_roles=['hr', 'admin'])
def updateBaseInfoPage(request, user_id):
    user = User.objects.get(id=user_id)

    form = UpdateUserForm(request.POST or None, instance=user)
    
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been updated')
            return redirect('/{}/view_user_info/'.format(user.id))

    context = {
        'form': form,
    }
    return render(request, 'user/update/update_base_info.html', context)


@allowed_users(allowed_roles=['hr', 'admin'])
def updateProfilePicturePage(request, user_id):
    user = User.objects.get(id=user_id)

    form = updateProfilePictureForm(request.POST or None, request.FILES or None, instance=user.userprofile)
    
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been updated')
            return redirect('/{}/view_user_info/'.format(user.id))

    context = {
        'user': user,
        'form': form,
    }
    return render(request, 'user/update/update_profile_picture.html', context)


@allowed_users(allowed_roles=['hr', 'admin'])
def deleteUserPage(request, user_id):
    user = User.objects.get(id=user_id)
    
    messages.success(request, 'User {} {} has been deleted'.format(user.first_name, user.last_name))
    user.delete()
    return redirect('/users/')


@allowed_users(allowed_roles=['hr', 'admin', 'employee', 'supervisor'])
def activityPage(request):
    user = request.user
    
    context = {
        'user': user
    }

    return render(request, 'user/activity_log.html', context)


@allowed_users(allowed_roles=['hr', 'admin'])
def updateUserprofileInfoPage(request, user_id):
    user = User.objects.get(id=user_id)
    group = user.groups.all()[0]

    if 'employee' == str(group):
        form = UpdateUserProfileEmployeeForm(request.POST or None, instance=user.userprofile)
    else:
        form = UpdateUserProfileForm(request.POST or None, instance=user.userprofile)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been updated')
            return redirect('/{}/view_user_info/'.format(user.id))

    context = {
        'form': form,
    }
    return render(request, 'user/update/update_userprofile_info.html', context)


@allowed_users(allowed_roles=['hr', 'admin'])
def updateSalaryInfoPage(request, user_id):
    user = User.objects.get(id=user_id)

    form = UpdateSalaryInfoForm(request.POST or None, instance=user.salaryinfo)
    
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been updated')
            return redirect('/{}/view_user_info/'.format(user.id))

    context = {
        'form': form,
    }
    return render(request, 'user/update/update_salaryinfo_info.html', context)


@allowed_users(allowed_roles=['hr', 'admin'])
def updateBankInfoPage(request, user_id):
    user = User.objects.get(id=user_id)
    form = UpdateBankInfoForm(request.POST or None, instance=user.bankinfo)



    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been updated')
            return redirect('/{}/view_user_info/'.format(user.id))

    context = {
        'form': form,
    }
    return render(request, 'user/update/update_bankinfo_info.html', context)


@unauthenticated_user
def loginPage(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['email'], password=cd['password'])
            if user:
                login(request, user)
                return redirect('/dashboard/')
            else:
                messages.info(request, 'Username or password is incorrect')
        
    context = {
        'form': LoginForm()
    }
    return render(request, 'user/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('/')


@allowed_users(allowed_roles=['admin', 'supervisor', 'hr'])
def users(request):
    userGroup = Group.objects.get(user=request.user).name

    # Filter only users who are related with supervisor by the SECTION 
    if userGroup == 'supervisor':
        users_all = User.objects.filter(groups__name='employee').filter(userprofile__boss=request.user.boss)
    # Admin can view all users in the database
    elif userGroup == 'admin':
        users_all = User.objects.exclude(id=request.user.id).all()
    # Admin can view all users in the database
    elif userGroup == 'hr':
        users_all = User.objects.exclude(id=request.user.id).all()
    # If users isn't a admin, hr or supervisor then redirect to dashbaord page
    else:
        return redirect('/dashboard')

    paginator = Paginator(users_all, 12)

    page = request.GET.get('page')
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    context = {
        'page': page,
        'users': users,
    }

    return render(request, 'user/users.html', context)


@login_required
def infoUser(request):
    user = request.user.id
    user = User.objects.get(id=user)

    context = {
        'user': user,
    }

    return render(request, 'user/info_about_you.html', context)


@login_required
def settingsPage(request):
    context = {}

    template = 'user/settings_page.html'

    return render(request, template, context)


@login_required
def changeUsername(request):
    template = 'user/change_username.html'
    form = UpdateUsernameForm(request.POST)
    if request.method == "POST":
        form = UpdateUsernameForm(request.POST or None)
        if form.is_valid():
            user = request.user
            username = request.POST.get('username')
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            if user.check_password(password1) and user.check_password(password2):
                user.username = username
                user.save()
                messages.success(request, "Your username has been changed successfully")

user/templates/user/activity_log.html
{% extends "ems/base.html" %}

{% block content %}

<style>
    .main_info{
        display: block;
        width: 270px;
        padding-right: 50px;
        float: left;
        font-size: 12px;
    }
    .base_info{
        font-weight: 500;
        font-size: 13px;
    }
</style>

<div class="row justify-content-center">
    <div class="col-lg-6">
        <!-- Dropdown Card Example -->
        <div class="card shadow mb-2">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Log Info</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <span class="main_info">Date create account: </span>
                    <div>
                        {% if not user.date_joined %}
                            <span class="base_info">Brak danych</span>
                        {% else %}
                            <span class="base_info">{{ user.date_joined }}</span>
                        {% endif %}
                    </div>
                <span class="main_info">Last Login: </span>
                    <div>
                        {% if not user.last_login %}
                            <span class="base_info">Brak danych</span>
                        {% else %}
                            <span class="base_info">{{ user.last_login }}</span>
                        {% endif %}
                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

user/templates/user/add_user.html
{% extends "ems/base.html" %}
<!-- Messages -->
{% block content %}
<style>
.form{
    margin-bottom: 15px;
}
</style>
<hr>
<div class="row justify-content-center">
    <div class='col-lg-6'>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-12 form">
                    <label for="validationServer01">Username</label>
                    {{form.username}}
                </div>
                <div class="col-lg-12 form">
                    <label for="validationServer01">First name</label>
                    {{form.first_name}}
                </div> 
                <div class="col-lg-12 form">
                    <label for="validationServer01">Last name</label>
                    {{form.last_name}}
                </div>
                <div class="col-lg-12 form">
                    <label for="validationServerUsername">Email</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupPrepend3">@</span>
                            </div>
                            {{form.email}}
                        </div>
                    </div>      
                <div class="col-lg-12 form">
                    <label for="validationServer01">Role user</label>
                        <select class="form-control" name="group_name">
                            {% for group in groups %}
                                <option name="group_name" value="{{ group.name }}">{{ group.name }}</option>
                            {% endfor %}
                        </select>
                </div>
            </div>
            <hr>
            <button class="btn btn-lg btn-primary" type="submit">Add employee</button>
        </form>
    </div>
</div>
{% endblock content %}

user/templates/user/change_username.html
{% extends "ems/base.html" %}

{% block titile %}
    Change password
{% endblock titile %}
{% load user_tags %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-lg-5">
        <!-- Circle Buttons -->
        <div class="card shadow mb-5">
            <div class="card-header py-3">
                <h2 class="m-0 font-weight-bold text-primary">Change username</h2>
            </div>
            <div class="card-body">
                <form method="POST" action="">
                {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-12 mb-3">
                            <label for="validationServer01">Username: </label>
                            {{form.username}}
                            <hr>
                            <label for="validationServer01">Password: </label>
                            {{form.password1}}
                            <hr>
                            <label for="validationServer01">Password confirmation:</label>
                            {{form.password2}}
                            <hr>
                            <input class="btn btn-lg btn-primary" type="submit" value="Change username">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

user/templates/user/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>EMS - Login</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  <style>
  .img-login{
    background-image: url({% static 'images/img-login.jpeg' %});
    background-size: 470px 400px;
    background-repeat: no-repeat;
  }

  </style>
</head>
<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block img-login"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">EMS!</h1>
                  </div>

                  <form method="POST" class="user">
                    {% csrf_token %}
                    <div class="form-group">
                      {{form.email}}
                     </div>
                    <div class="form-group">
                      {{form.password}}
					          </div>
                    <input class="btn btn-primary btn-user btn-block" type="submit" value="Login">                 
                    <hr>
                  </form>

                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                {% include "ems/messages.html" %}

                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

user/templates/user/settings_page.html
{% extends "ems/base.html" %}
{% block title %}
    Settings Page
{% endblock title %}
{% block content %}

{% include "ems/messages.html" %}

<style>
    .limits{
        display: block;
        width:300px;
        padding-right: 50px;
        float: left;
    }
    .limit_info{
        font-weight: 900;
        font-size: 16px;
    }
</style>

<div class="row justify-content-center">
    <div class="col-lg-5">
        <!-- Circle Buttons -->
        <div class="card shadow mb-5">
            <div class="card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">Change a password</h3>
            </div>
            <div class="card-body text-center">
                <code>Change your password</code>
                <hr>
                <a href="{% url 'user:password_change' %}" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-flag"></i>
                </span>
                <span class="text">Change password</span>
                </a>
            </div>
        </div>
        <div class="card shadow mb-5">
            <div class="card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">Change a username</h3>
            </div>
            <div class="card-body text-center">
                <h4 class="font-weight-bold mb-3">Your current username: {{ request.user.username }}</h4>
                <hr>
                <code>Change your username (this is the text you use for the login)</code>
                <hr>
                <a href="{% url 'user:change_username' %}" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-flag"></i>
                </span>
                <span class="text">Change username</span>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

user/templates/user/users.html
{% extends "ems/base.html" %}
{% load static %}

{% block content %}
{% include "ems/messages.html" %}

<!-- Display users -->
<h2 class="mb-4">Employees</h2>

<div class="row">
{% for u in users %}
  <div class="w3-container mb-4 col-lg-6 col-sm-12 col-md-12">
    <ul class="w3-ul w3-card-4">
      <li class="w3-bar">
        <img src="{{ u.userprofile.image.url }}" class="w3-bar-item w3-circle w3-hide-small" style="width:100px">
        <div class="w3-bar-item">
          <span class="w3-xlarge">{{u.username}}</span><br>
          <span>Stanowisko: {% if u.userprofile.possition == None %} No data. Fill information {% else %}{{u.userprofile.possition}} {% endif %}</span><br>
          <span>Dział: {% if u.userprofile.section == None %} No data. Fill information {% else %}{{u.userprofile.section}} {% endif %}</span>
        </div>
          {% comment %} <a class="btn btn-lg btn-primary mt-4 mr-2 float-right" href="{% url 'user:update_employee' u.id %}">Update Info</a> {% endcomment %}
          <a class="btn btn-lg btn-primary mt-4 mr-2 float-right" href="{% url 'user:view_user_info' u.id %}">View</a>
      </li>
    </ul>
  </div>


{% endfor %}
<div class="col-lg-12 col-sm-12 col-md-12">
  {% include "user/pagination/pagination_users.html" with page=users %}
</div>
</div>


{% endblock content %}